import { JunctionData, ANPRVehicleRecord, AuditBlock, AgentDecisionRecord } from './types';

export const RAIPUR_JUNCTIONS: JunctionData[] = [
  {
    id: 'RPR_GE_ROAD_01',
    name: 'Jaistambh Chowk',
    code: 'JST-01',
    location: 'Central Commercial Hub, GE Road',
    lat: 21.2385,
    lng: 81.6337,
    currentPhase: 'NORMAL_CYCLE',
    phaseRemainingSec: 24,
    queuePcu: 42,
    averageDelaySec: 68,
    emergencyActive: false,
    rfSignalDbm: -68,
    linkLatencyMs: 42,
    signals: {
      NORTH_BOUND: { red: false, yellow: false, green: true, priorityOverlay: false },
      SOUTH_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
      EAST_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
      WEST_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
    },
  },
  {
    id: 'RPR_GE_ROAD_02',
    name: 'Ghadi Chowk',
    code: 'GHD-02',
    location: 'Administrative Hub / High Court Link',
    lat: 21.2428,
    lng: 81.6394,
    currentPhase: 'NORMAL_CYCLE',
    phaseRemainingSec: 18,
    queuePcu: 35,
    averageDelaySec: 54,
    emergencyActive: false,
    rfSignalDbm: -72,
    linkLatencyMs: 44,
    signals: {
      NORTH_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
      SOUTH_BOUND: { red: false, yellow: false, green: true, priorityOverlay: false },
      EAST_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
      WEST_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
    },
  },
  {
    id: 'RPR_GE_ROAD_03',
    name: 'Telibandha Chowk',
    code: 'TLB-03',
    location: 'Marine Drive Arterial Junction',
    lat: 21.2412,
    lng: 81.6672,
    currentPhase: 'NORMAL_CYCLE',
    phaseRemainingSec: 32,
    queuePcu: 29,
    averageDelaySec: 46,
    emergencyActive: false,
    rfSignalDbm: -75,
    linkLatencyMs: 46,
    signals: {
      NORTH_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
      SOUTH_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
      EAST_BOUND: { red: false, yellow: false, green: true, priorityOverlay: false },
      WEST_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
    },
  },
  {
    id: 'RPR_MEKAHARA_01',
    name: 'Dr. BR Ambedkar Memorial Hospital Gate',
    code: 'MKH-04',
    location: 'Mekahara Emergency Trauma Terminal',
    lat: 21.2471,
    lng: 81.6514,
    currentPhase: 'NORMAL_CYCLE',
    phaseRemainingSec: 15,
    queuePcu: 16,
    averageDelaySec: 22,
    emergencyActive: false,
    rfSignalDbm: -64,
    linkLatencyMs: 38,
    signals: {
      NORTH_BOUND: { red: false, yellow: false, green: true, priorityOverlay: false },
      SOUTH_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
      EAST_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
      WEST_BOUND: { red: true, yellow: false, green: false, priorityOverlay: false },
    },
  },
];

export const INITIAL_ANPR_LOGS: ANPRVehicleRecord[] = [
  {
    id: 'VEH-001',
    timestamp: '21:32:15',
    plate: 'CG-04-MB-1080',
    vehicleType: '108_AMBULANCE',
    confidence: 0.984,
    speedKmh: 48,
    crossedStopLineOnRed: true,
    yieldingToEmergency: false,
    status: 'EXEMPT_GOOD_SAMARITAN',
    challanAmountInr: 0,
    exemptReason: 'Primary Emergency Vehicle in Transit to Mekahara Hospital',
    strobeFrequencyHz: 1.84,
  },
  {
    id: 'VEH-002',
    timestamp: '21:32:18',
    plate: 'CG-04-NA-4492',
    vehicleType: 'CITIZEN_CAR',
    confidence: 0.941,
    speedKmh: 14,
    crossedStopLineOnRed: true,
    yieldingToEmergency: true,
    status: 'EXEMPT_GOOD_SAMARITAN',
    challanAmountInr: 0,
    exemptReason: 'Yielded stop-line to clear lane for Ambulance CG-04-MB-1080',
  },
  {
    id: 'VEH-003',
    timestamp: '21:32:20',
    plate: 'CG-04-KB-8821',
    vehicleType: 'TWO_WHEELER',
    confidence: 0.965,
    speedKmh: 12,
    crossedStopLineOnRed: true,
    yieldingToEmergency: true,
    status: 'EXEMPT_GOOD_SAMARITAN',
    challanAmountInr: 0,
    exemptReason: 'Good Samaritan stop-line offset maneuver (Sec 177 MVA Exempted)',
  },
  {
    id: 'VEH-004',
    timestamp: '21:31:40',
    plate: '22-BH-4491-AB',
    vehicleType: 'CITIZEN_CAR',
    confidence: 0.932,
    speedKmh: 38,
    crossedStopLineOnRed: true,
    yieldingToEmergency: false,
    status: 'VIOLATION_PENALIZED',
    challanAmountInr: 1000,
    exemptReason: 'Unlawful stop-line jump (No active emergency preemption active)',
  },
  {
    id: 'VEH-005',
    timestamp: '21:30:12',
    plate: 'CG-04-TP-0044',
    vehicleType: 'POLICE_PATROL',
    confidence: 0.991,
    speedKmh: 34,
    crossedStopLineOnRed: false,
    yieldingToEmergency: false,
    status: 'COMPLIANT',
    challanAmountInr: 0,
  },
];

export const INITIAL_AUDIT_BLOCKS: AuditBlock[] = [
  {
    blockHeight: 1482,
    timestamp: '2026-09-17T16:02:14Z',
    junctionId: 'RPR_GE_ROAD_01 (Jaistambh)',
    overrideSource: 'HANDHELD_RF_REMOTE_02',
    vehicleClass: '108_AMBULANCE',
    primaryPlate: 'CG-04-MB-1080',
    preemptionDurationSec: 22,
    whitelistedPlates: ['CG-04-NA-4492', 'CG-04-KB-8821'],
    prevHash: '8b9c43a290bf41e2d8376510a76c8e31a980c6f5d210b37c6a51d08e43ef1902',
    blockHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    isTamperProof: true,
  },
  {
    blockHeight: 1481,
    timestamp: '2026-09-17T15:44:02Z',
    junctionId: 'RPR_GE_ROAD_02 (Ghadi Chowk)',
    overrideSource: 'CCTV_EDGE_AI_ORIN',
    vehicleClass: 'FIRE_TENDER',
    primaryPlate: 'CG-04-A-1011',
    preemptionDurationSec: 28,
    whitelistedPlates: ['CG-04-ZZ-9912'],
    prevHash: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    blockHash: '8b9c43a290bf41e2d8376510a76c8e31a980c6f5d210b37c6a51d08e43ef1902',
    isTamperProof: true,
  },
];

export const INITIAL_AGENT_STATES: AgentDecisionRecord[] = [
  {
    agentName: 'Preemption Decision Orchestrator',
    agentRole: 'Central Consensus & Multi-Agent Arbitration',
    status: 'VERIFIED',
    confidence: 0.98,
    executionMs: 12.4,
    actionSummary: 'Consensus reached: 5.5s inter-green clearance scheduled, priority green granted for North Bound lane.',
    evidence: [
      'Strobe frequency 1.84 Hz verified within 1.0–2.5 Hz band',
      'Queue depth: 42 PCU, dynamic priority ceiling: 22.0s',
      'Form-C relays mechanically locked against East/West greens',
    ],
  },
  {
    agentName: 'Emergency Vehicle Verification Agent',
    agentRole: 'Multimodal Chassis & Rooftop Strobe Anti-Spoofing',
    status: 'VERIFIED',
    confidence: 0.984,
    executionMs: 33.2,
    actionSummary: 'Verified 108 Ambulance chassis with active flashing optical beacon.',
    evidence: [
      'YOLOv8 chassis confidence: 98.4%',
      'Rooftop ROI optical beacon frequency: 1.84 Hz (anti-spoof pass)',
      'Decoy probability: <0.02%',
    ],
  },
  {
    agentName: 'IRC:SP:12 Policy & Timing Agent',
    agentRole: 'Deterministic Deceleration & Queue Dissipation Math',
    status: 'VERIFIED',
    confidence: 1.0,
    executionMs: 4.1,
    actionSummary: 'Calculated clearance: 3.5s Yellow + 2.0s All-Red + 22.0s Emergency Green.',
    evidence: [
      'IRC:SP:12 compliant yellow interval: 3.5s for 40 km/h approach',
      'All-Red inter-green clearance: 2.0s clearing 24m junction box',
      'Zero probability of dual conflicting green feeds',
    ],
  },
  {
    agentName: 'Good Samaritan Whitelist Agent',
    agentRole: 'Stop-Line Yielding Tracker & Automated e-Challan Waiver',
    status: 'ACTIVE',
    confidence: 0.965,
    executionMs: 18.7,
    actionSummary: 'Whitelisted 2 citizen vehicles yielding across red stop-line.',
    evidence: [
      'CG-04-NA-4492: Offset trajectory to clear lane 1 (MVA Sec 177 waiver)',
      'CG-04-KB-8821: Stop-line crossed during preemption window (No challan)',
      'Direct MQTT payload dispatched to Raipur Commissionerate ICCC',
    ],
  },
  {
    agentName: 'Corridor Preemption & Escalation Agent',
    agentRole: '868 MHz Sub-GHz RF Ingestion & Watchdog Ceiling',
    status: 'VERIFIED',
    confidence: 0.99,
    executionMs: 1.6,
    actionSummary: '868 MHz RF signal decoded in 42ms with +14 dB link penetration margin.',
    evidence: [
      'Transceiver RSSI: -68 dBm through commercial chassis metal',
      'AES-128 HMAC-SHA256 anti-replay nonce verified',
      'Watchdog ceiling armed at 30.0s hard cutoff',
    ],
  },
  {
    agentName: 'Audit & Cryptographic Governance Agent',
    agentRole: 'Append-Only SHA-256 Chained Preemption Ledger',
    status: 'VERIFIED',
    confidence: 1.0,
    executionMs: 2.3,
    actionSummary: 'Generated Block #1482 hash and chained to Raipur Police storage.',
    evidence: [
      'Previous Block Hash verified: 8b9c43a...',
      'Current Block Hash: e3b0c44... (SHA-256)',
      'Non-repudiation audit package archived for court inspection',
    ],
  },
];
